### Merging Demographic and Spending Data

In [21]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# load and merge files
transaction_data = pd.read_excel("kartdata1.xlsx")
demographical_data = pd.read_excel("demografik.xlsx")

df_fs = pd.merge(transaction_data, demographical_data, on="Customer_id", how="left")
df_fs.to_excel("df_fs.xlsx", index=False)

Exception ignored in: <function ZipFile.__del__ at 0x000002A0A94039C0>
Traceback (most recent call last):
  File "c:\ProgramData\anaconda3\Lib\zipfile.py", line 1872, in __del__
    self.close()
  File "c:\ProgramData\anaconda3\Lib\zipfile.py", line 1874, in close
    def close(self):

KeyboardInterrupt:

KeyboardInterrupt:

### Adding Slope, MA and Churn Columns to the Data

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
df_fs = pd.read_excel("df_fs.xlsx")
slope_df = pd.read_csv("slope.csv")
MA_df = pd.read_csv("MA.csv")
df_fs["trxdate"] = pd.to_datetime(df_fs["trxdate"]).dt.strftime('%Y-%m')
churn_df = pd.read_csv("churn_analysis.csv")
merged_df = pd.merge(df_fs, churn_df, how="left", on=["Customer_id", "trxdate"])
merged_df = pd.merge(merged_df, slope_df, how="left", on=["Customer_id", "trxdate"])
merged_df = pd.merge(merged_df, MA_df, how="left", on=["Customer_id", "trxdate"])
merged_df.head()

,Customer_id,trxdate,max_taksit,qty,TotalAmountLC,total_amount_market,total_qty_count_market,total_amount_diger,total_qty_count_diger,total_amount_giyim,...,Age,EmploymentType,EmployerSector,JobTitle,City,County,Churn,Slope,Unnamed: 0,Moving_Average
0,97425780,2024-03,0,1,340.00,NaN,NaN,340.00,1.0,NaN,...,30,Serbest Meslek Sahibi,Özel Kurum,Unvan Yok,Şanlıurfa,Siverek,0,-2.900325,579355.0,321.427143
1,97425780,2023-09,5,1,710.00,NaN,NaN,710.00,1.0,NaN,...,30,Serbest Meslek Sahibi,Özel Kurum,Unvan Yok,Şanlıurfa,Siverek,0,0.000000,579349.0,0.000000
2,97425780,2023-12,5,1,710.00,NaN,NaN,710.00,1.0,NaN,...,30,Serbest Meslek Sahibi,Özel Kurum,Unvan Yok,Şanlıurfa,Siverek,1,0.000000,579352.0,355.000000
3,97425780,2023-08,5,1,710.00,NaN,NaN,710.00,1.0,NaN,...,30,Serbest Meslek Sahibi,Özel Kurum,Unvan Yok,Şanlıurfa,Siverek,1,0.000000,579348.0,0.000000
4,97425780,2024-01,0,1,119.99,NaN,NaN,119.99,1.0,NaN,...,30,Serbest Meslek Sahibi,Özel Kurum,Unvan Yok,Şanlıurfa,Siverek,0,0.000000,579353.0,284.000000

In [ ]:
merged_df.to_excel("merged_df.xlsx")

### Saving prepared file as an Excel file

In [23]:
import pandas as pd
merged_df= pd.read_excel("merged_df.xlsx")

### Checking Null Values

In [24]:
merged_df.isnull().sum()

Unnamed: 0.1                            0
Customer_id                             0
trxdate                                 0
max_taksit                              0
qty                                     0
TotalAmountLC                           0
total_amount_market                123443
total_qty_count_market             123443
total_amount_diger                 109923
total_qty_count_diger              109923
total_amount_giyim                 286029
total_qty_count_giyim              286029
total_amount_saglik_kozmetik       316018
total_qty_count_saglik_kozmetik    316018
total_amount_sigorta               407822
total_qty_count_sigorta            407822
total_amount_teknoloji             338836
total_qty_count_teknoloji          338836
total_amount_ulasim                252845
total_qty_count_ulasim             252845
total_amount_yemek                 271016
total_qty_count_yemek              271016
Accommodation                           0
BranchName                              0
Unnamed: 3                         465999
Citizenship                             0
Gender                                  0
MaritalStatus                          38
ProfessionCode                          0
ValueSegment                            0
RecordingTime                           0
sesLevel                                2
EducationLevelPI                        0
Age                                     0
EmploymentType                        805
EmployerSector                       3765
JobTitle                             2869
City                                38129
County                              38148
Churn                                   0
Slope                               42121
Unnamed: 0                          42121
Moving_Average                      42121
dtype: int64

### Changing Null Values of Spending Categories with 0

In [25]:
MCCPI = [
    "total_amount_market",
    "total_qty_count_market",
    "total_amount_diger",
    "total_qty_count_diger",
    "total_amount_giyim",
    "total_qty_count_giyim",
    "total_amount_saglik_kozmetik",
    "total_qty_count_saglik_kozmetik",
    "total_amount_sigorta",
    "total_qty_count_sigorta",
    "total_amount_teknoloji",
    "total_qty_count_teknoloji",
    "total_amount_ulasim",
    "total_qty_count_ulasim",
    "total_amount_yemek",
    "total_qty_count_yemek"
]

merged_df[MCCPI] = merged_df[MCCPI].fillna(0)


print(merged_df.isnull().sum())

Unnamed: 0.1                            0
Customer_id                             0
trxdate                                 0
max_taksit                              0
qty                                     0
TotalAmountLC                           0
total_amount_market                     0
total_qty_count_market                  0
total_amount_diger                      0
total_qty_count_diger                   0
total_amount_giyim                      0
total_qty_count_giyim                   0
total_amount_saglik_kozmetik            0
total_qty_count_saglik_kozmetik         0
total_amount_sigorta                    0
total_qty_count_sigorta                 0
total_amount_teknoloji                  0
total_qty_count_teknoloji               0
total_amount_ulasim                     0
total_qty_count_ulasim                  0
total_amount_yemek                      0
total_qty_count_yemek                   0
Accommodation                           0
BranchName                              0
Unnamed: 3                         465999
Citizenship                             0
Gender                                  0
MaritalStatus                          38
ProfessionCode                          0
ValueSegment                            0
RecordingTime                           0
sesLevel                                2
EducationLevelPI                        0
Age                                     0
EmploymentType                        805
EmployerSector                       3765
JobTitle                             2869
City                                38129
County                              38148
Churn                                   0
Slope                               42121
Unnamed: 0                          42121
Moving_Average                      42121
dtype: int64

### Deleting Unnamed Column

In [26]:
merged_df = merged_df.drop(columns=merged_df.columns[merged_df.columns.str.contains('Unnamed')])
print(merged_df.head())

   Customer_id  trxdate  max_taksit  qty  TotalAmountLC  total_amount_market  \
0     97425780  2024-03           0    1         340.00                  0.0
1     97425780  2023-09           5    1         710.00                  0.0
2     97425780  2023-12           5    1         710.00                  0.0
3     97425780  2023-08           5    1         710.00                  0.0
4     97425780  2024-01           0    1         119.99                  0.0

   total_qty_count_market  total_amount_diger  total_qty_count_diger  \
0                     0.0              340.00                    1.0
1                     0.0              710.00                    1.0
2                     0.0              710.00                    1.0
3                     0.0              710.00                    1.0
4                     0.0              119.99                    1.0

   total_amount_giyim  ...  EducationLevelPI  Age         EmploymentType  \
0                 0.0  ...                 6   30  Serbest Meslek Sahibi
1                 0.0  ...                 6   30  Serbest Meslek Sahibi
2                 0.0  ...                 6   30  Serbest Meslek Sahibi
3                 0.0  ...                 6   30  Serbest Meslek Sahibi
4                 0.0  ...                 6   30  Serbest Meslek Sahibi

   EmployerSector   JobTitle       City   County  Churn     Slope  \
0      Özel Kurum  Unvan Yok  Şanlıurfa  Siverek      0 -2.900325
1      Özel Kurum  Unvan Yok  Şanlıurfa  Siverek      0  0.000000
2      Özel Kurum  Unvan Yok  Şanlıurfa  Siverek      1  0.000000
3      Özel Kurum  Unvan Yok  Şanlıurfa  Siverek      1  0.000000
4      Özel Kurum  Unvan Yok  Şanlıurfa  Siverek      0  0.000000

   Moving_Average
0      321.427143
1        0.000000
2      355.000000
3        0.000000
4      284.000000

[5 rows x 40 columns]

### Handling the Null Values

In [27]:
import pandas as pd

null_marital_row = merged_df[merged_df['MaritalStatus'].isnull()]

boş_customer_ids = null_marital_row['Customer_id']

merged_df = merged_df[~merged_df['Customer_id'].isin(boş_customer_ids)]

silinen_satır_sayısı = len(null_marital_row)
print("Number of Deleted Rows:", silinen_satır_sayısı)

Silinen satır sayısı: 38

### Handling Null Values of EmployerSector

In [28]:
import pandas as pd

#Replacing some EmployerSector values with "Sektör Yok"
condition = merged_df['EmploymentType'].isin(['Çalışmıyor', 'Emekli Çalışan', 'Serbest Meslek Sahibi'])
merged_df.loc[condition, 'EmployerSector'] = 'Sektör Yok'
 
# Delete Null values whose Employment type is Ücretli
isveren_df = merged_df[(merged_df['EmploymentType'] == 'Ücretli') & (merged_df['EmployerSector'].isnull())]
for customer_id in isveren_df['Customer_id'].unique():
    rows_to_drop = merged_df[merged_df['Customer_id'] == customer_id]
    merged_df.drop(rows_to_drop.index, inplace=True)

#For "İşveren" EmploymentType, set EmployerSector as "Özel Kurum" 
isveren_indexes = merged_df.index[merged_df['EmploymentType'] == 'İşveren']
merged_df.loc[isveren_indexes, 'EmployerSector'] = 'Özel Kurum'

#For 'Tacir/Esnaf' EmploymentType, set EmployerSector as "Özel Kurum" 
esnaf_indexes = merged_df.index[merged_df['EmploymentType'] == 'Tacir/Esnaf']
merged_df.loc[esnaf_indexes, 'EmployerSector'] = 'Özel Kurum'
 
# Filling the rest of null values as "Sektör Yok"
merged_df['EmployerSector'].fillna('Sektör Yok', inplace=True)
 
print(merged_df.isnull().sum())
 
unique_customers = merged_df[merged_df['EmployerSector'].isnull()]['Customer_id'].unique()
for customer_id in unique_customers:
    Employment_type = merged_df.loc[merged_df['Customer_id'] == customer_id, 'EmploymentType'].iloc[0]
    print(f"Customer ID: {customer_id}, EmploymentType: {Employment_type}")

Customer_id                            0
trxdate                                0
max_taksit                             0
qty                                    0
TotalAmountLC                          0
total_amount_market                    0
total_qty_count_market                 0
total_amount_diger                     0
total_qty_count_diger                  0
total_amount_giyim                     0
total_qty_count_giyim                  0
total_amount_saglik_kozmetik           0
total_qty_count_saglik_kozmetik        0
total_amount_sigorta                   0
total_qty_count_sigorta                0
total_amount_teknoloji                 0
total_qty_count_teknoloji              0
total_amount_ulasim                    0
total_qty_count_ulasim                 0
total_amount_yemek                     0
total_qty_count_yemek                  0
Accommodation                          0
BranchName                             0
Citizenship                            0
Gender                                 0
MaritalStatus                          0
ProfessionCode                         0
ValueSegment                           0
RecordingTime                          0
sesLevel                               2
EducationLevelPI                       0
Age                                    0
EmploymentType                       805
EmployerSector                         0
JobTitle                            2754
City                               38077
County                             38096
Churn                                  0
Slope                              42030
Moving_Average                     42030
dtype: int64

### Filling Null Values of City with the City information of BranchName Column

In [29]:
import pandas as pd

cities_of_branch = pd.read_excel("CitiesofBranch.xlsx")

null_city_rows = merged_df[merged_df['City'].isnull()]

for index, row in null_city_rows.iterrows():
    branch_name = row['BranchName']
    
    city_name = cities_of_branch.loc[cities_of_branch['branchname'] == branch_name, 'CityName'].values
    
    if len(city_name) > 0:
        merged_df.at[index, 'City'] = city_name[0]

print(merged_df.head(10))

   Customer_id  trxdate  max_taksit  qty  TotalAmountLC  total_amount_market  \
0     97425780  2024-03           0    1         340.00                 0.00
1     97425780  2023-09           5    1         710.00                 0.00
2     97425780  2023-12           5    1         710.00                 0.00
3     97425780  2023-08           5    1         710.00                 0.00
4     97425780  2024-01           0    1         119.99                 0.00
5     97425780  2024-02           0    1         468.00                 0.00
6     97425734  2023-09           4   30       28885.30              1034.64
7     97425734  2023-08           0   26       18669.50              6997.63
8     97425734  2023-07           3   35       16782.61              6682.06
9     97425734  2023-11           4   41       19916.13              4741.78

   total_qty_count_market  total_amount_diger  total_qty_count_diger  \
0                     0.0              340.00                    1.0
1                     0.0              710.00                    1.0
2                     0.0              710.00                    1.0
3                     0.0              710.00                    1.0
4                     0.0              119.99                    1.0
5                     0.0              468.00                    1.0
6                     2.0            13722.28                    8.0
7                     2.0             5657.00                    2.0
8                     5.0             2501.56                    4.0
9                     4.0             7779.91                    8.0

   total_amount_giyim  ...  EducationLevelPI  Age         EmploymentType  \
0                0.00  ...                 6   30  Serbest Meslek Sahibi
1                0.00  ...                 6   30  Serbest Meslek Sahibi
2                0.00  ...                 6   30  Serbest Meslek Sahibi
3                0.00  ...                 6   30  Serbest Meslek Sahibi
4                0.00  ...                 6   30  Serbest Meslek Sahibi
5                0.00  ...                 6   30  Serbest Meslek Sahibi
6             2600.00  ...                 8   62                 Emekli
7                0.00  ...                 8   62                 Emekli
8             4245.07  ...                 8   62                 Emekli
9              525.00  ...                 8   62                 Emekli

   EmployerSector            JobTitle       City   County  Churn     Slope  \
0      Sektör Yok           Unvan Yok  Şanlıurfa  Siverek      0 -2.900325
1      Sektör Yok           Unvan Yok  Şanlıurfa  Siverek      0  0.000000
2      Sektör Yok           Unvan Yok  Şanlıurfa  Siverek      1  0.000000
3      Sektör Yok           Unvan Yok  Şanlıurfa  Siverek      1  0.000000
4      Sektör Yok           Unvan Yok  Şanlıurfa  Siverek      0  0.000000
5      Sektör Yok           Unvan Yok  Şanlıurfa  Siverek      0  0.831000
6      Özel Kurum  Üst Düzey Yönetici   İstanbul    Fatih      0 -0.112431
7      Özel Kurum  Üst Düzey Yönetici   İstanbul    Fatih      0  0.044392
8      Özel Kurum  Üst Düzey Yönetici   İstanbul    Fatih      0       NaN
9      Özel Kurum  Üst Düzey Yönetici   İstanbul    Fatih      0  0.527189

   Moving_Average
0      321.427143
1        0.000000
2      355.000000
3        0.000000
4      284.000000
5      355.000000
6    16782.610000
7        0.000000
8             NaN
9    21445.803333

[10 rows x 40 columns]

### Deleting Unnecessary Columns

In [30]:
columns_to_drop = [ "BranchName", "County"] 
merged_df.drop(columns=columns_to_drop, inplace=True)

### Filling Null JobTitle Values

Find what is the ProfessionCodes of the Job Titles that have Null Values

In [31]:

pd.set_option('display.max_rows', None)
unique_jobtitles = merged_df['JobTitle'].unique()
print('Values that JobTitle can take: ', unique_jobtitles)

null_jobtitle_rows = merged_df[merged_df['JobTitle'].isnull()]
ProfessionCode_JobTitle_null = null_jobtitle_rows['ProfessionCode'].unique()
print('Profession Codes that has null Job Titles: ', ProfessionCode_JobTitle_null )

Values that JobTitle can take:  ['Unvan Yok' 'Üst Düzey Yönetici' 'Pratisyen' 'Memur'
 'Orta Düzey Yönetici' 'Müdür' 'Yetkili' 'Uzman Doktor' 'Müdür Yrd.'
 'Uzman' 'Çalışan' 'İşyeri Sahibi' 'Asteğmen' 'İmam' 'Okutman' 'Astsubay'
 'Araştırma Görevlisi' 'Başhekim' 'Uzman Asker' 'Profesör' 'Doktor' 'Vaiz'
 'Müezzin' nan 'Doçent' 'Teğmen' 'Binbaşı' 'Üsteğmen' 'Subay' 'General'
 'Yüzbaşı' 'Albay' 'Yönetici']
Profession Codes that has null Job Titles:  [ 17  25  39  24  38  60  14  83  62  87  13   4  40 101  32  34  50  36
   7  33  30  35  44  15  43   0  10   8  42  27  98   2  28  58   9  79
  29  57  48  81  73  64   6  11  55  91  67   5]

As the ProfessionCodes has no Titles, replace Jobtitles with "Unvan Yok"

In [32]:
merged_df['JobTitle'].fillna('Unvan Yok', inplace=True)

### Deleting the Customer Data Which has Null SesLevels

In [ ]:
null_sesLevel_customer_ids = merged_df[merged_df['sesLevel'].isnull()]['Customer_id'].unique()

merged_df = merged_df[~merged_df['Customer_id'].isin(null_sesLevel_customer_ids)]

print("Churn değeri Null olan Customer_id'ler:", len(null_sesLevel_customer_ids))
print("\nTemizlenmiş DataFrame:")

### Filling Null Values of MA and Slope with 0

In [ ]:
merged_df['Moving_Average'].fillna(0, inplace=True)
merged_df['Slope'].fillna(0, inplace=True)
merged_df.isnull().sum()

### Handling Null Values of EmploymentType

Understand Which Profession Codes has Null EmploymentTypes

In [35]:
import pandas as pd
 
unique_Employment_types = merged_df["EmploymentType"].unique()
 
null_employment_df = merged_df[merged_df['EmploymentType'].isnull()]["ProfessionCode"]
unique_professionCode = null_employment_df.unique()

print(unique_Employment_types)
print(unique_professionCode)

['Serbest Meslek Sahibi' 'Emekli' 'Emekli Çalışan' 'Öğrenci' 'Ücretli'
 'Çalışmıyor' 'İşveren' 'Tacir/Esnaf' nan]
[17 83 38 32 39 25 24 30 60 55 50 34]

Assigning Appropriate EmploymentTypes for Different ProfessionCodes

In [36]:

null_employment_df = merged_df[(merged_df['EmploymentType'].isnull()) & 
                               (merged_df['ProfessionCode'].isin([17, 83, 32, 30, 39, 38, 25, 24, 60, 55, 34, 50]))]
 
for index, row in null_employment_df.iterrows():
    profession_code = row['ProfessionCode']
    if profession_code in [17, 38]:
        merged_df.at[index, 'EmploymentType'] = 'Çalışmıyor'
    elif profession_code in [25, 83]:
        merged_df.at[index, 'EmploymentType'] = 'Tacir/Esnaf'
    else:
        merged_df.at[index, 'EmploymentType'] = 'Ücretli'

### Handling Data Types

In [37]:
merged_df.dtypes

Customer_id                                 int64
trxdate                                    object
max_taksit                                  int64
qty                                         int64
TotalAmountLC                             float64
total_amount_market                       float64
total_qty_count_market                    float64
total_amount_diger                        float64
total_qty_count_diger                     float64
total_amount_giyim                        float64
total_qty_count_giyim                     float64
total_amount_saglik_kozmetik              float64
total_qty_count_saglik_kozmetik           float64
total_amount_sigorta                      float64
total_qty_count_sigorta                   float64
total_amount_teknoloji                    float64
total_qty_count_teknoloji                 float64
total_amount_ulasim                       float64
total_qty_count_ulasim                    float64
total_amount_yemek                        float64
total_qty_count_yemek                     float64
Accommodation                               int64
Citizenship                                 int64
Gender                                      int64
MaritalStatus                             float64
ProfessionCode                              int64
ValueSegment                               object
RecordingTime                      datetime64[ns]
sesLevel                                  float64
EducationLevelPI                            int64
Age                                         int64
EmploymentType                             object
EmployerSector                             object
JobTitle                                   object
City                                       object
Churn                                       int64
Slope                                     float64
Moving_Average                            float64
dtype: object

### Changing Recording Time to Tenure

In [38]:
import pandas as pd

today_date = pd.to_datetime('today').strftime('%Y-%m-%d')

merged_df['RecordingTime'] = pd.to_datetime(merged_df['RecordingTime']).dt.strftime('%Y-%m-%d')

merged_df['Tenure'] = (pd.to_datetime(today_date) - pd.to_datetime(merged_df['RecordingTime'])).dt.days / 365
merged_df.drop(columns=['RecordingTime'], inplace=True)

### Encoding the ValueSegment

In [39]:
ValueSegment_encoded = pd.get_dummies(merged_df['ValueSegment'], prefix='ValueSegment')

ValueSegment_encoded = ValueSegment_encoded.astype(int)

merged_df = pd.concat([merged_df, ValueSegment_encoded], axis=1)

merged_df.drop('ValueSegment', axis=1, inplace=True)

print(merged_df.head())

   Customer_id  trxdate  max_taksit  qty  TotalAmountLC  total_amount_market  \
0     97425780  2024-03           0    1         340.00                  0.0
1     97425780  2023-09           5    1         710.00                  0.0
2     97425780  2023-12           5    1         710.00                  0.0
3     97425780  2023-08           5    1         710.00                  0.0
4     97425780  2024-01           0    1         119.99                  0.0

   total_qty_count_market  total_amount_diger  total_qty_count_diger  \
0                     0.0              340.00                    1.0
1                     0.0              710.00                    1.0
2                     0.0              710.00                    1.0
3                     0.0              710.00                    1.0
4                     0.0              119.99                    1.0

   total_amount_giyim  ...       City  Churn     Slope  Moving_Average  \
0                 0.0  ...  Şanlıurfa      0 -2.900325      321.427143
1                 0.0  ...  Şanlıurfa      0  0.000000        0.000000
2                 0.0  ...  Şanlıurfa      1  0.000000      355.000000
3                 0.0  ...  Şanlıurfa      1  0.000000        0.000000
4                 0.0  ...  Şanlıurfa      0  0.000000      284.000000

     Tenure  ValueSegment_A1  ValueSegment_A2  ValueSegment_B  ValueSegment_C  \
0  2.635616                0                0               0               1
1  2.635616                0                0               0               1
2  2.635616                0                0               0               1
3  2.635616                0                0               0               1
4  2.635616                0                0               0               1

   ValueSegment_D
0               0
1               0
2               0
3               0
4               0

[5 rows x 42 columns]

### Encoding the JobTitle

In [40]:
JobTitle_encoded = pd.get_dummies(merged_df['JobTitle'], prefix='JobTitle')

JobTitle_encoded = JobTitle_encoded.astype(int)

merged_df = pd.concat([merged_df, JobTitle_encoded], axis=1)

merged_df.drop('JobTitle', axis=1, inplace=True)

print(merged_df.head())

   Customer_id  trxdate  max_taksit  qty  TotalAmountLC  total_amount_market  \
0     97425780  2024-03           0    1         340.00                  0.0
1     97425780  2023-09           5    1         710.00                  0.0
2     97425780  2023-12           5    1         710.00                  0.0
3     97425780  2023-08           5    1         710.00                  0.0
4     97425780  2024-01           0    1         119.99                  0.0

   total_qty_count_market  total_amount_diger  total_qty_count_diger  \
0                     0.0              340.00                    1.0
1                     0.0              710.00                    1.0
2                     0.0              710.00                    1.0
3                     0.0              710.00                    1.0
4                     0.0              119.99                    1.0

   total_amount_giyim  ...  JobTitle_Uzman Doktor  JobTitle_Vaiz  \
0                 0.0  ...                      0              0
1                 0.0  ...                      0              0
2                 0.0  ...                      0              0
3                 0.0  ...                      0              0
4                 0.0  ...                      0              0

   JobTitle_Yetkili  JobTitle_Yönetici  JobTitle_Yüzbaşı  JobTitle_Çalışan  \
0                 0                  0                 0                 0
1                 0                  0                 0                 0
2                 0                  0                 0                 0
3                 0                  0                 0                 0
4                 0                  0                 0                 0

   JobTitle_Üst Düzey Yönetici  JobTitle_Üsteğmen  JobTitle_İmam  \
0                            0                  0              0
1                            0                  0              0
2                            0                  0              0
3                            0                  0              0
4                            0                  0              0

   JobTitle_İşyeri Sahibi
0                       0
1                       0
2                       0
3                       0
4                       0

[5 rows x 73 columns]

### Encoding the EmploymentType

In [41]:
EmploymentType_encoded = pd.get_dummies(merged_df['EmploymentType'], prefix='EmploymentType')

EmploymentType_encoded = EmploymentType_encoded.astype(int)

merged_df = pd.concat([merged_df, EmploymentType_encoded], axis=1)

merged_df.drop('EmploymentType', axis=1, inplace=True)

print(merged_df.head())

   Customer_id  trxdate  max_taksit  qty  TotalAmountLC  total_amount_market  \
0     97425780  2024-03           0    1         340.00                  0.0
1     97425780  2023-09           5    1         710.00                  0.0
2     97425780  2023-12           5    1         710.00                  0.0
3     97425780  2023-08           5    1         710.00                  0.0
4     97425780  2024-01           0    1         119.99                  0.0

   total_qty_count_market  total_amount_diger  total_qty_count_diger  \
0                     0.0              340.00                    1.0
1                     0.0              710.00                    1.0
2                     0.0              710.00                    1.0
3                     0.0              710.00                    1.0
4                     0.0              119.99                    1.0

   total_amount_giyim  ...  JobTitle_İmam  JobTitle_İşyeri Sahibi  \
0                 0.0  ...              0                       0
1                 0.0  ...              0                       0
2                 0.0  ...              0                       0
3                 0.0  ...              0                       0
4                 0.0  ...              0                       0

   EmploymentType_Emekli  EmploymentType_Emekli Çalışan  \
0                      0                              0
1                      0                              0
2                      0                              0
3                      0                              0
4                      0                              0

   EmploymentType_Serbest Meslek Sahibi  EmploymentType_Tacir/Esnaf  \
0                                     1                           0
1                                     1                           0
2                                     1                           0
3                                     1                           0
4                                     1                           0

   EmploymentType_Çalışmıyor  EmploymentType_Öğrenci  EmploymentType_Ücretli  \
0                          0                       0                       0
1                          0                       0                       0
2                          0                       0                       0
3                          0                       0                       0
4                          0                       0                       0

   EmploymentType_İşveren
0                       0
1                       0
2                       0
3                       0
4                       0

[5 rows x 80 columns]

### Encoding the EmployerSector

In [42]:
EmployerSector_encoded = pd.get_dummies(merged_df['EmployerSector'], prefix='EmployerSector')

EmployerSector_encoded = EmployerSector_encoded.astype(int)

merged_df = pd.concat([merged_df, EmployerSector_encoded], axis=1)

merged_df.drop('EmployerSector', axis=1, inplace=True)

print(merged_df.head(2))
print(merged_df.dtypes)

   Customer_id  trxdate  max_taksit  qty  TotalAmountLC  total_amount_market  \
0     97425780  2024-03           0    1          340.0                  0.0
1     97425780  2023-09           5    1          710.0                  0.0

   total_qty_count_market  total_amount_diger  total_qty_count_diger  \
0                     0.0               340.0                    1.0
1                     0.0               710.0                    1.0

   total_amount_giyim  ...  EmploymentType_Emekli Çalışan  \
0                 0.0  ...                              0
1                 0.0  ...                              0

   EmploymentType_Serbest Meslek Sahibi  EmploymentType_Tacir/Esnaf  \
0                                     1                           0
1                                     1                           0

   EmploymentType_Çalışmıyor  EmploymentType_Öğrenci  EmploymentType_Ücretli  \
0                          0                       0                       0
1                          0                       0                       0

   EmploymentType_İşveren  EmployerSector_Kamu Kurumu  \
0                       0                           0
1                       0                           0

   EmployerSector_Sektör Yok  EmployerSector_Özel Kurum
0                          1                          0
1                          1                          0

[2 rows x 82 columns]
Customer_id                               int64
trxdate                                  object
max_taksit                                int64
qty                                       int64
TotalAmountLC                           float64
total_amount_market                     float64
total_qty_count_market                  float64
total_amount_diger                      float64
total_qty_count_diger                   float64
total_amount_giyim                      float64
total_qty_count_giyim                   float64
total_amount_saglik_kozmetik            float64
total_qty_count_saglik_kozmetik         float64
total_amount_sigorta                    float64
total_qty_count_sigorta                 float64
total_amount_teknoloji                  float64
total_qty_count_teknoloji               float64
total_amount_ulasim                     float64
total_qty_count_ulasim                  float64
total_amount_yemek                      float64
total_qty_count_yemek                   float64
Accommodation                             int64
Citizenship                               int64
Gender                                    int64
MaritalStatus                           float64
ProfessionCode                            int64
sesLevel                                float64
EducationLevelPI                          int64
Age                                       int64
City                                     object
Churn                                     int64
Slope                                   float64
Moving_Average                          float64
Tenure                                  float64
ValueSegment_A1                           int32
ValueSegment_A2                           int32
ValueSegment_B                            int32
ValueSegment_C                            int32
ValueSegment_D                            int32
JobTitle_Albay                            int32
JobTitle_Araştırma Görevlisi              int32
JobTitle_Asteğmen                         int32
JobTitle_Astsubay                         int32
JobTitle_Başhekim                         int32
JobTitle_Binbaşı                          int32
JobTitle_Doktor                           int32
JobTitle_Doçent                           int32
JobTitle_General                          int32
JobTitle_Memur                            int32
JobTitle_Müdür                            int32
JobTitle_Müdür Yrd.                       int32
JobTitle_Müezzin                          int32
JobTitle_Okutman                          int32
JobTitle_Orta Düzey Yönetici              int32
JobTitle_Pratisyen                        int32
JobTitle_Profesör                         int32
JobTitle_Subay                            int32
JobTitle_Teğmen                           int32
JobTitle_Unvan Yok                        int32
JobTitle_Uzman                            int32
JobTitle_Uzman Asker                      int32
JobTitle_Uzman Doktor                     int32
JobTitle_Vaiz                             int32
JobTitle_Yetkili                          int32
JobTitle_Yönetici                         int32
JobTitle_Yüzbaşı                          int32
JobTitle_Çalışan                          int32
JobTitle_Üst Düzey Yönetici               int32
JobTitle_Üsteğmen                         int32
JobTitle_İmam                             int32
JobTitle_İşyeri Sahibi                    int32
EmploymentType_Emekli                     int32
EmploymentType_Emekli Çalışan             int32
EmploymentType_Serbest Meslek Sahibi      int32
EmploymentType_Tacir/Esnaf                int32
EmploymentType_Çalışmıyor                 int32
EmploymentType_Öğrenci                    int32
EmploymentType_Ücretli                    int32
EmploymentType_İşveren                    int32
EmployerSector_Kamu Kurumu                int32
EmployerSector_Sektör Yok                 int32
EmployerSector_Özel Kurum                 int32
dtype: object

### Changing City with Geographical Region

In [43]:
geographical_regions = {
    'Marmara': ['Edirne', 'Kırklareli', 'Tekirdağ', 'İstanbul', 'Kocaeli', 'Yalova', 'Sakarya', 'Bilecik', 'Bursa', 'Balıkesir', 'Çanakkale'],
    'İç Anadolu': ['Aksaray', 'Ankara', 'Çankırı', 'Eskişehir', 'Karaman', 'Kırıkkale', 'Kırşehir', 'Konya', 'Nevşehir', 'Niğde', 'Sivas', 'Yozgat', 'Kayseri'],
    'Ege': ['İzmir', 'Manisa', 'Aydın', 'Denizli', 'Kütahya', 'Afyonkarahisar', 'Uşak', 'Muğla'],
    'Akdeniz': ['Adana', 'Osmaniye', 'Antalya', 'Burdur', 'Hatay', 'Isparta', 'Mersin', 'Kahramanmaraş'],
    'Karadeniz': ['Rize', 'Trabzon', 'Artvin', 'Sinop', 'Tokat', 'Çorum', 'Amasya', 'Samsun', 'Zonguldak', 'Bolu', 'Düzce', 'Karabük', 'Bartın', 'Kastamonu', 'Bayburt', 'Giresun', 'Gümüşhane', 'Ordu'],
    'Doğu Anadolu': ['Ağrı', 'Ardahan', 'Bingöl', 'Bitlis', 'Elazığ', 'Erzincan', 'Erzurum', 'Hakkari', 'Iğdır', 'Kars', 'Malatya', 'Muş', 'Tunceli', 'Van', 'Şırnak'],
    'Güneydoğu Anadolu': ['Adıyaman', 'Batman', 'Diyarbakır', 'Gaziantep', 'Kilis', 'Mardin', 'Siirt', 'Şanlıurfa']
}

def get_region(city):
    for region, cities in geographical_regions.items():
        if city in cities:
            return region
    return None

merged_df['GeographicalRegion'] = merged_df['City'].apply(get_region)

print(merged_df[['City', 'GeographicalRegion']].tail(12))
print(merged_df.dtypes)

           City GeographicalRegion
465987   Manisa                Ege
465988   Manisa                Ege
465989   Manisa                Ege
465990   Manisa                Ege
465991   Manisa                Ege
465992   Manisa                Ege
465993   Manisa                Ege
465994   Manisa                Ege
465995   Manisa                Ege
465996  Malatya       Doğu Anadolu
465997  Malatya       Doğu Anadolu
465998  Malatya       Doğu Anadolu
Customer_id                               int64
trxdate                                  object
max_taksit                                int64
qty                                       int64
TotalAmountLC                           float64
total_amount_market                     float64
total_qty_count_market                  float64
total_amount_diger                      float64
total_qty_count_diger                   float64
total_amount_giyim                      float64
total_qty_count_giyim                   float64
total_amount_saglik_kozmetik            float64
total_qty_count_saglik_kozmetik         float64
total_amount_sigorta                    float64
total_qty_count_sigorta                 float64
total_amount_teknoloji                  float64
total_qty_count_teknoloji               float64
total_amount_ulasim                     float64
total_qty_count_ulasim                  float64
total_amount_yemek                      float64
total_qty_count_yemek                   float64
Accommodation                             int64
Citizenship                               int64
Gender                                    int64
MaritalStatus                           float64
ProfessionCode                            int64
sesLevel                                float64
EducationLevelPI                          int64
Age                                       int64
City                                     object
Churn                                     int64
Slope                                   float64
Moving_Average                          float64
Tenure                                  float64
ValueSegment_A1                           int32
ValueSegment_A2                           int32
ValueSegment_B                            int32
ValueSegment_C                            int32
ValueSegment_D                            int32
JobTitle_Albay                            int32
JobTitle_Araştırma Görevlisi              int32
JobTitle_Asteğmen                         int32
JobTitle_Astsubay                         int32
JobTitle_Başhekim                         int32
JobTitle_Binbaşı                          int32
JobTitle_Doktor                           int32
JobTitle_Doçent                           int32
JobTitle_General                          int32
JobTitle_Memur                            int32
JobTitle_Müdür                            int32
JobTitle_Müdür Yrd.                       int32
JobTitle_Müezzin                          int32
JobTitle_Okutman                          int32
JobTitle_Orta Düzey Yönetici              int32
JobTitle_Pratisyen                        int32
JobTitle_Profesör                         int32
JobTitle_Subay                            int32
JobTitle_Teğmen                           int32
JobTitle_Unvan Yok                        int32
JobTitle_Uzman                            int32
JobTitle_Uzman Asker                      int32
JobTitle_Uzman Doktor                     int32
JobTitle_Vaiz                             int32
JobTitle_Yetkili                          int32
JobTitle_Yönetici                         int32
JobTitle_Yüzbaşı                          int32
JobTitle_Çalışan                          int32
JobTitle_Üst Düzey Yönetici               int32
JobTitle_Üsteğmen                         int32
JobTitle_İmam                             int32
JobTitle_İşyeri Sahibi                    int32
EmploymentType_Emekli                     int32
EmploymentType_Emekli Çalışan             int32
EmploymentType_Serbest Meslek Sahibi      int32
EmploymentType_Tacir/Esnaf                int32
EmploymentType_Çalışmıyor                 int32
EmploymentType_Öğrenci                    int32
EmploymentType_Ücretli                    int32
EmploymentType_İşveren                    int32
EmployerSector_Kamu Kurumu                int32
EmployerSector_Sektör Yok                 int32
EmployerSector_Özel Kurum                 int32
GeographicalRegion                       object
dtype: object

### Encoding the Geographical  Region

In [44]:
GeographicalRegion_encoded = pd.get_dummies(merged_df['GeographicalRegion'], prefix='GeographicalRegion')

GeographicalRegion_encoded = GeographicalRegion_encoded.astype(int)

merged_df = pd.concat([merged_df, GeographicalRegion_encoded], axis=1)

merged_df.drop('City', axis=1, inplace=True)
merged_df.drop('GeographicalRegion', axis=1, inplace=True)

print(merged_df.tail(2))
print(merged_df.dtypes)

        Customer_id  trxdate  max_taksit  qty  TotalAmountLC  \
465997     16082019  2023-07           0    2         119.99
465998     16082019  2024-03           0    5        1465.26

        total_amount_market  total_qty_count_market  total_amount_diger  \
465997                  0.0                     0.0              119.99
465998                472.1                     1.0              993.16

        total_qty_count_diger  total_amount_giyim  ...  \
465997                    2.0                 0.0  ...
465998                    2.0                 0.0  ...

        EmployerSector_Kamu Kurumu  EmployerSector_Sektör Yok  \
465997                           0                          0
465998                           0                          0

        EmployerSector_Özel Kurum  GeographicalRegion_Akdeniz  \
465997                          1                           0
465998                          1                           0

        GeographicalRegion_Doğu Anadolu  GeographicalRegion_Ege  \
465997                                1                       0
465998                                1                       0

        GeographicalRegion_Güneydoğu Anadolu  GeographicalRegion_Karadeniz  \
465997                                     0                             0
465998                                     0                             0

        GeographicalRegion_Marmara  GeographicalRegion_İç Anadolu
465997                           0                              0
465998                           0                              0

[2 rows x 88 columns]
Customer_id                               int64
trxdate                                  object
max_taksit                                int64
qty                                       int64
TotalAmountLC                           float64
total_amount_market                     float64
total_qty_count_market                  float64
total_amount_diger                      float64
total_qty_count_diger                   float64
total_amount_giyim                      float64
total_qty_count_giyim                   float64
total_amount_saglik_kozmetik            float64
total_qty_count_saglik_kozmetik         float64
total_amount_sigorta                    float64
total_qty_count_sigorta                 float64
total_amount_teknoloji                  float64
total_qty_count_teknoloji               float64
total_amount_ulasim                     float64
total_qty_count_ulasim                  float64
total_amount_yemek                      float64
total_qty_count_yemek                   float64
Accommodation                             int64
Citizenship                               int64
Gender                                    int64
MaritalStatus                           float64
ProfessionCode                            int64
sesLevel                                float64
EducationLevelPI                          int64
Age                                       int64
Churn                                     int64
Slope                                   float64
Moving_Average                          float64
Tenure                                  float64
ValueSegment_A1                           int32
ValueSegment_A2                           int32
ValueSegment_B                            int32
ValueSegment_C                            int32
ValueSegment_D                            int32
JobTitle_Albay                            int32
JobTitle_Araştırma Görevlisi              int32
JobTitle_Asteğmen                         int32
JobTitle_Astsubay                         int32
JobTitle_Başhekim                         int32
JobTitle_Binbaşı                          int32
JobTitle_Doktor                           int32
JobTitle_Doçent                           int32
JobTitle_General                          int32
JobTitle_Memur                            int32
JobTitle_Müdür                            int32
JobTitle_Müdür Yrd.                       int32
JobTitle_Müezzin                          int32
JobTitle_Okutman                          int32
JobTitle_Orta Düzey Yönetici              int32
JobTitle_Pratisyen                        int32
JobTitle_Profesör                         int32
JobTitle_Subay                            int32
JobTitle_Teğmen                           int32
JobTitle_Unvan Yok                        int32
JobTitle_Uzman                            int32
JobTitle_Uzman Asker                      int32
JobTitle_Uzman Doktor                     int32
JobTitle_Vaiz                             int32
JobTitle_Yetkili                          int32
JobTitle_Yönetici                         int32
JobTitle_Yüzbaşı                          int32
JobTitle_Çalışan                          int32
JobTitle_Üst Düzey Yönetici               int32
JobTitle_Üsteğmen                         int32
JobTitle_İmam                             int32
JobTitle_İşyeri Sahibi                    int32
EmploymentType_Emekli                     int32
EmploymentType_Emekli Çalışan             int32
EmploymentType_Serbest Meslek Sahibi      int32
EmploymentType_Tacir/Esnaf                int32
EmploymentType_Çalışmıyor                 int32
EmploymentType_Öğrenci                    int32
EmploymentType_Ücretli                    int32
EmploymentType_İşveren                    int32
EmployerSector_Kamu Kurumu                int32
EmployerSector_Sektör Yok                 int32
EmployerSector_Özel Kurum                 int32
GeographicalRegion_Akdeniz                int32
GeographicalRegion_Doğu Anadolu           int32
GeographicalRegion_Ege                    int32
GeographicalRegion_Güneydoğu Anadolu      int32
GeographicalRegion_Karadeniz              int32
GeographicalRegion_Marmara                int32
GeographicalRegion_İç Anadolu             int32
dtype: object

Save the Cleaned Data

In [50]:
merged_df.to_csv("cleanedData.csv")